{% set name = "apache-airflow-providers-redis" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_redis-{{ version }}.tar.gz
  sha256: 4f03a92f6d40c85d0b8491750659fda1fdaf3d51958494411c659267af7e3369

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - redis-py >=4.5.2,!=4.5.5,!=5.0.2

test:
  imports:
    - airflow.providers.redis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-redis for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/redis/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-redis/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
